"""Tests for the legacy → OKF bundle migration tool."""

from __future__ import annotations

from pathlib import Path

import pytest

from lwiki.conformance import is_conformant, validate_bundle
from lwiki.migrate import convert


def _make_legacy_wiki(root: Path) -> None:
    """Build a tiny Obsidian-shaped wiki for migration tests."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "AGENTS.md").write_text(
        "# Greek Wiki Schema\n\n## Domain\nGreek history\n",
        encoding="utf-8",
    )
    (root / "CLAUDE.md").write_text("@AGENTS.md\n", encoding="utf-8")
    (root / "raw").mkdir()
    (root / "raw" / "files.log").write_text(
        "# Auto-generated by lwiki. Do not edit manually.\n"
        "# filename | sha256 | last_updated\n"
        "intro.md | deadbeef | 2026-01-01\n",
        encoding="utf-8",
    )
    (root / "raw" / "intro.md").write_text("Source material.\n", encoding="utf-8")
    wiki = root / "wiki"
    (wiki / "concepts").mkdir(parents=True)
    (wiki / "entities").mkdir(parents=True)
    (wiki / "summaries").mkdir(parents=True)
    (wiki / "index.md").write_text("# Wiki Index\n", encoding="utf-8")
    (wiki / "log.md").write_text(
        "# Wiki Log\n\n## [2026-01-01] init | greek\n", encoding="utf-8"
    )
    (wiki / "overview.md").write_text(
        "---\ntitle: Overview\ntype: overview\n"
        "description: Big picture.\ntags: [overview]\nupdated: 2026-01-01\n---\n\n"
        "See [[democracy]].\n",
        encoding="utf-8",
    )
    (wiki / "concepts" / "democracy.md").write_text(
        "---\ntitle: Democracy\ntype: concept\n"
        "description: Athenian democracy.\ntags: [politics]\nupdated: 2026-01-02\n"
        "sources: [raw/intro.md]\n---\n\n"
        "Refers to [[athens]].\n",
        encoding="utf-8",
    )
    (wiki / "entities" / "athens.md").write_text(
        "---\ntitle: Athens\ntype: entity\ndescription: City.\nupdated: 2026-01-03\n---\n\n"
        "Body.\n",
        encoding="utf-8",
    )
    (wiki / "summaries" / "intro.md").write_text(
        "---\ntitle: Intro\ntype: summary\ndescription: A summary.\n"
        "updated: 2026-01-04\nsources: [raw/intro.md]\n---\n\n"
        "Summary body. See [[democracy]].\n",
        encoding="utf-8",
    )


# --- happy path ---


def test_convert_basic(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    result = convert(old, new)
    assert result.pages_migrated >= 3  # overview + concepts + entities + summaries
    # Lifted files
    assert (new / "AGENTS.md").is_file()
    assert (new / "CLAUDE.md").is_file()
    assert (new / "index.md").is_file()
    assert (new / "log.md").is_file()
    assert (new / "overview.md").is_file()
    assert (new / "README.md").is_file()
    # Concept subdirs lifted, no wiki/ wrapper
    assert (new / "concepts" / "democracy.md").is_file()
    assert (new / "entities" / "athens.md").is_file()
    assert (new / "summaries" / "intro.md").is_file()
    assert not (new / "wiki").exists()


def test_convert_preserves_raw_files_log(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    convert(old, new)
    assert (new / "raw" / "files.log").is_file()
    assert (new / "raw" / "intro.md").is_file()


def test_convert_rewrites_wikilinks(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    result = convert(old, new)
    assert result.links_rewritten >= 3  # overview→democracy, democracy→athens, summary→democracy
    overview = (new / "overview.md").read_text(encoding="utf-8")
    assert "[democracy](concepts/democracy.md)" in overview
    assert "[[democracy]]" not in overview


def test_convert_frontmatter_to_okf_shape(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    convert(old, new)
    democracy = (new / "concepts" / "democracy.md").read_text(encoding="utf-8")
    # `updated:` gone
    assert "updated:" not in democracy
    # `generated:` present with both keys
    assert "generated:" in democracy
    assert "by: lwiki-migrate/0.1" in democracy
    # YAML may quote the ISO date or not depending on the writer
    assert ("at: 2026-01-02" in democracy) or ("at: '2026-01-02'" in democracy)
    # `sources:` is now an OKF list of mappings
    assert "resource: raw/intro.md" in democracy


def test_convert_overview_uses_okf_frontmatter(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    convert(old, new)
    overview = (new / "overview.md").read_text(encoding="utf-8")
    assert overview.startswith("---")
    assert "type: overview" in overview
    assert "generated:" in overview


def test_convert_root_index_declares_okf_version(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    convert(old, new)
    index = (new / "index.md").read_text(encoding="utf-8")
    assert "okf_version: '0.2'" in index


def test_convert_result_is_conformant(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    convert(old, new)
    violations = validate_bundle(new)
    assert is_conformant(violations), violations


# --- guards ---


def test_convert_rejects_non_legacy_source(tmp_path: Path) -> None:
    """A directory without AGENTS.md + wiki/ isn't a legacy wiki."""
    bad = tmp_path / "bad"
    bad.mkdir()
    with pytest.raises(FileNotFoundError):
        convert(bad, tmp_path / "out")


def test_convert_refuses_non_empty_output(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    new.mkdir()
    (new / "existing.md").write_text("x", encoding="utf-8")
    _make_legacy_wiki(old)
    with pytest.raises(FileExistsError):
        convert(old, new)
    # Force overwrite succeeds
    result = convert(old, new, force=True)
    assert result.pages_migrated >= 3


def test_convert_source_is_unchanged(tmp_path: Path) -> None:
    """Migration is read-only on the source."""
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    snapshot = (old / "wiki" / "concepts" / "democracy.md").read_text(encoding="utf-8")
    convert(old, new)
    assert (old / "wiki" / "concepts" / "democracy.md").read_text(encoding="utf-8") == snapshot


# --- insight pages get verified: instead of cited ---


def test_insight_pages_get_verified_frontmatter(tmp_path: Path) -> None:
    old = tmp_path / "old"
    new = tmp_path / "new"
    _make_legacy_wiki(old)
    # Add an insight with cited:
    (old / "wiki" / "insights").mkdir(parents=True, exist_ok=True)
    (old / "wiki" / "insights" / "synthesis.md").write_text(
        "---\ntitle: Synthesis\ntype: insight\ndescription: An insight.\n"
        "updated: 2026-02-01\ncited: [democracy, athens]\n"
        "sources: [raw/intro.md]\n---\n\nBody.\n",
        encoding="utf-8",
    )
    convert(old, new)
    insight = (new / "insights" / "synthesis.md").read_text(encoding="utf-8")
    assert "cited:" not in insight
    assert "verified:" in insight
    assert "by: democracy" in insight or "by: athens" in insight