"""Track files in raw/ vs files.log (SHA-256)."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import date
from pathlib import Path

LOG_FILENAME = "files.log"
IGNORED = frozenset({LOG_FILENAME, ".gitkeep", ".DS_Store"})


def sha256_of_file(filepath: Path) -> str:
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def scan_directory(raw_dir: Path) -> dict[str, str]:
    """Scan raw/ and return {filename: sha256} for all tracked files."""
    files: dict[str, str] = {}
    if not raw_dir.is_dir():
        return files
    for item in sorted(raw_dir.iterdir()):
        if item.is_file() and item.name not in IGNORED and not item.name.startswith("."):
            files[item.name] = sha256_of_file(item)
        elif item.is_dir() and item.name not in IGNORED and not item.name.startswith("."):
            files.update(scan_directory(item))
    return files


def read_log(log_path: Path) -> dict[str, str]:
    """Read files.log and return {filename: sha256}."""
    entries: dict[str, str] = {}
    if not log_path.exists():
        return entries
    with open(log_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 2:
                entries[parts[0]] = parts[1]
    return entries


def write_log(log_path: Path, files: dict[str, str], generator: str = "lwiki") -> None:
    """Write files.log with current file states."""
    with open(log_path, "w", encoding="utf-8") as f:
        f.write(f"# Auto-generated by {generator}. Do not edit manually.\n")
        f.write("# filename | sha256 | last_updated\n")
        today = date.today().isoformat()
        for name in sorted(files.keys()):
            f.write(f"{name} | {files[name]} | {today}\n")


@dataclass(frozen=True)
class DriftResult:
    new_files: frozenset[str]
    deleted_files: frozenset[str]
    modified_files: frozenset[str]

    @property
    def has_drift(self) -> bool:
        return bool(self.new_files or self.deleted_files or self.modified_files)


def compute_drift(raw_dir: Path) -> DriftResult:
    """Compare raw/ on disk to files.log."""
    log_path = raw_dir / LOG_FILENAME
    current_files = scan_directory(raw_dir)
    logged_files = read_log(log_path)

    current_names = set(current_files.keys())
    logged_names = set(logged_files.keys())

    new_files = current_names - logged_names
    deleted_files = logged_names - current_names
    common_files = current_names & logged_names
    modified_files = {f for f in common_files if current_files[f] != logged_files[f]}

    return DriftResult(
        new_files=frozenset(new_files),
        deleted_files=frozenset(deleted_files),
        modified_files=frozenset(modified_files),
    )


def format_drift_report(result: DriftResult) -> str:
    """Human-readable report (no trailing newline on empty sections)."""
    lines: list[str] = []
    if not result.has_drift:
        return "No changes detected in raw/."

    if result.new_files:
        lines.append(f"New files ({len(result.new_files)}):")
        for f in sorted(result.new_files):
            lines.append(f"  + {f}")

    if result.deleted_files:
        lines.append(f"Deleted files ({len(result.deleted_files)}):")
        for f in sorted(result.deleted_files):
            lines.append(f"  - {f}")

    if result.modified_files:
        lines.append(f"Modified files ({len(result.modified_files)}):")
        for f in sorted(result.modified_files):
            lines.append(f"  ~ {f}")

    if result.new_files:
        lines.append("")
        lines.append(
            f"Consider running wiki ingest to process {len(result.new_files)} new source(s)."
        )
    if result.deleted_files:
        lines.append("")
        lines.append(
            f"Warning: {len(result.deleted_files)} file(s) deleted from raw/ "
            "but may still be referenced in wiki."
        )

    return "\n".join(lines)


def run_raw_status(raw_dir: Path) -> tuple[int, str]:
    """
    Status only: no writes.
    Exit code 0 if no drift, 1 if drift, 2 if raw_dir invalid.
    """
    if not raw_dir.is_dir():
        return 2, f"Error: {raw_dir} is not a directory"
    result = compute_drift(raw_dir)
    report = format_drift_report(result)
    code = 0 if not result.has_drift else 1
    return code, report


def run_raw_sync(raw_dir: Path) -> tuple[int, str]:
    """
    Write files.log to match raw/. Returns 0 on success, 2 if raw_dir invalid.
    Always succeeds with exit 0 if directory exists (per spec: sync completes cleanly).
    """
    if not raw_dir.is_dir():
        return 2, f"Error: {raw_dir} is not a directory"
    current_files = scan_directory(raw_dir)
    log_path = raw_dir / LOG_FILENAME
    write_log(log_path, current_files)
    n = len(current_files)
    return 0, f"files.log updated ({n} files tracked)."
